database:
  uri: ${DATABASE_URI:localhost:5435}
spring:
  application:
    name: stock-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${database.uri}/stock?createDatabaseIfNotExist=true&useUnicode=true&&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:valentina}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://${database.uri}/stock
    user: valentina
    password: password
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: ${ISSUER_URI:http://localhost:9000/realms/master}
          issuer-uri: ${ISSUER_URI:https://localhost:9000/realms/master}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  mail:
    port: 587
    username: testingemailacount@gmail.com
    password: ebsw lxga bjcq graq
    host: smtp.gmail.com
    fromuser: testingemailacount@gmail.com
    displayname: testingemailacount@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  auth:
    converter:
      resource-id: drug-system
      principal-attribute: preferred_username
server:
  port: 8082
  servlet:
    context-path: /stock-service
logging:
  pattern.console: "%d{yyyyMMdd HH:mm:ss} %-5level %logger{36}:%L - %msg%n"
  level:
    root: INFO
    org:
      springframework:
        security: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/drug-discovery/eureka}
  instance:
    preferIpAddress: true

kafka:
  bootstrap-address: ${KAFKA_URI:localhost:9092}
  prescription-topic: prescription-topic
auth-server:
  trust-store:
    jks: ${AUTH_SERVER_TRUST_STORE_PATH:/certs/drug-store.jks}
    password: ${AUTH_SERVER_TRUST_STORE_PASSWORD:valentina}