apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: default
spec:
  selector:
    app: keycloak
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000