server:
  port: 8761
  servlet:
    context-path: "/drug-discovery"
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000