apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-service-deployment
  namespace: default
  labels:
    app: prescription-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription-service
  template:
    metadata:
      labels:
        app: prescription-service
    spec:
      containers:
        - name: prescription-service
          image: baisnake/prescription-service:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: ISSUER_URI
              value: "http://192.168.1.6:9000/realms/master"
            - name: EUREKA_URI
              value: "http://drug-discovery-service.default.svc.cluster.local:8761/drug-discovery/eureka"
            - name: DATABASE_WRITE_URI
              value: "prescription-db-master-service.default.svc.cluster.local:5434"
            - name: DATABASE_READ_URI
              value: "prescription-db-slave-service.default.svc.cluster.local:5436"
            - name: KAFKA_URI
              value: "kafka-service.default.svc.cluster.local:9092"
          ports:
            - containerPort: 8081